var deployed_contract = "0xa896365cb53aac22072faab30f8abd5fcd415386";

contracts = {};
ctrAddresses = {};
contracts["EVMDB"] = {
	interface: [{"constant":true,"inputs":[],"name":"get_number_of_DBs","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_row","type":"uint256"}],"name":"get_row","outputs":[{"name":"","type":"bytes32[]"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_data","type":"bytes32[]"}],"name":"insert","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_name","type":"bytes32"},{"name":"_headers","type":"bytes32[]"}],"name":"create","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_DB_id","type":"uint256"}],"name":"get_header","outputs":[{"name":"","type":"bytes32[]"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_DB_id","type":"uint256"}],"name":"get_DB_info","outputs":[{"name":"","type":"address"},{"name":"","type":"bytes32"},{"name":"","type":"int256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_row","type":"uint256"}],"name":"erase","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_row","type":"uint256"},{"name":"_data","type":"bytes32[]"}],"name":"update","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_value","type":"bytes32"}],"name":"search","outputs":[{"name":"","type":"int256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_row","type":"uint256"},{"name":"_col","type":"uint256"}],"name":"get_row_col","outputs":[{"name":"","type":"bytes32"}],"payable":false,"type":"function"},{"inputs":[],"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"name","type":"bytes32"},{"indexed":false,"name":"index","type":"uint256"}],"name":"DBCreated","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"db","type":"uint256"},{"indexed":false,"name":"row","type":"uint256"}],"name":"RowInserted","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"db","type":"uint256"},{"indexed":false,"name":"row","type":"uint256"}],"name":"RowUpdated","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"db","type":"uint256"},{"indexed":false,"name":"row","type":"uint256"}],"name":"RowErased","type":"event"}],
	address: deployed_contract
};
contracts["EVMDB"].contractClass = web3.eth.contract(contracts["EVMDB"].interface);
contracts["EVMDB"].contract = contracts["EVMDB"].contractClass.at(contracts["EVMDB"].address);
contracts["<EVMDB - 0>"] = {
	interface: [{"constant":true,"inputs":[],"name":"get_number_of_DBs","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_row","type":"uint256"}],"name":"get_row","outputs":[{"name":"","type":"bytes32[]"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_data","type":"bytes32[]"}],"name":"insert","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_name","type":"bytes32"},{"name":"_headers","type":"bytes32[]"}],"name":"create","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_DB_id","type":"uint256"}],"name":"get_header","outputs":[{"name":"","type":"bytes32[]"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_DB_id","type":"uint256"}],"name":"get_DB_info","outputs":[{"name":"","type":"address"},{"name":"","type":"bytes32"},{"name":"","type":"int256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_row","type":"uint256"}],"name":"erase","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_row","type":"uint256"},{"name":"_data","type":"bytes32[]"}],"name":"update","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_value","type":"bytes32"}],"name":"search","outputs":[{"name":"","type":"int256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_DB_id","type":"uint256"},{"name":"_row","type":"uint256"},{"name":"_col","type":"uint256"}],"name":"get_row_col","outputs":[{"name":"","type":"bytes32"}],"payable":false,"type":"function"},{"inputs":[],"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"name","type":"bytes32"},{"indexed":false,"name":"index","type":"uint256"}],"name":"DBCreated","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"db","type":"uint256"},{"indexed":false,"name":"row","type":"uint256"}],"name":"RowInserted","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"db","type":"uint256"},{"indexed":false,"name":"row","type":"uint256"}],"name":"RowUpdated","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"db","type":"uint256"},{"indexed":false,"name":"row","type":"uint256"}],"name":"RowErased","type":"event"}],
	address: deployed_contract
};
contracts["<EVMDB - 0>"].contractClass = web3.eth.contract(contracts["<EVMDB - 0>"].interface);
contracts["<EVMDB - 0>"].contract = contracts["<EVMDB - 0>"].contractClass.at(contracts["<EVMDB - 0>"].address);
if (!ctrAddresses["EVMDB"]){ ctrAddresses["EVMDB"] = [] }ctrAddresses["EVMDB"].push(deployed_contract)
